name: Pré Rotinas

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Entrar na pasta backend
        run: cd backend

      - name: Instalar dependências do Composer
        run: composer install

      - name: Executar Migrates
        run: php spark migrate

      - name: Executar Seed Empresas
        run: php spark db:seed Empresas

      - name: Executar Seed Usuarios
        run: php spark db:seed Usuarios

      - name: Executar Seed Configurações
        run: php spark db:seed Configuracoes

      - name: Executar Seed Permissões
        run: php spark db:seed Permissoes

      - name: Executar Seed Municipios
        run: php spark db:seed Municipios

      - name: Executar Seed Natureza Operação
        run: php spark db:seed NaturezaOperacao

      - name: Executar Seed Status NFe
        run: php spark db:seed StatusNFe
